#!/bin/bash
# Quick Reference - HybridSecScan Testing

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║      HYBRIDSCAN - QUICK REFERENCE FOR TESTING                 ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Function to print section
print_section() {
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  $1"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
}

print_section "1️⃣  QUICK START"
echo ""
echo "   📱 Dashboard:      http://localhost:5173"
echo "   🔌 Backend API:    http://localhost:8000"
echo "   📚 API Docs:       http://localhost:8000/docs"
echo ""

print_section "2️⃣  SAST TESTING (Static Analysis)"
echo ""
echo "   FILE: ProgramasPruebas/vulnerable_app.py"
echo ""
echo "   STEPS:"
echo "   1. Open: http://localhost:5173"
echo "   2. Tab: SAST"
echo "   3. Upload: vulnerable_app.py"
echo "   4. Tool: Bandit"
echo "   5. Click: 'Ejecutar Auditoría'"
echo "   6. Watch: Progress bar increases 0→100%"
echo "   7. Result: 16 vulnerabilities detected"
echo ""

print_section "3️⃣  DAST TESTING (Dynamic Analysis)"
echo ""
echo "   OPTION A: Remote URL (Fastest)"
echo "   ─────────────────────────────"
echo "   URL: https://juice-shop.herokuapp.com/"
echo "   Time: ~5 min"
echo ""
echo "   OPTION B: Local Docker (Better control)"
echo "   ────────────────────────────────────"
echo "   Command: ./ProgramasPruebas/launch_vulnerable_apps.ps1"
echo "   Select: Option 1 (Juice Shop)"
echo "   Wait: App starts at http://localhost:3000/"
echo "   Time: ~10-15 min"
echo ""
echo "   THEN IN HYBRIDSCAN:"
echo "   ──────────────────"
echo "   1. Open: http://localhost:5173"
echo "   2. Tab: DAST"
echo "   3. Enter URL: http://localhost:3000/ (or remote)"
echo "   4. Click: 'Ejecutar Auditoría'"
echo "   5. Watch: Progress bar running"
echo "   6. Result: OWASP ZAP findings"
echo ""

print_section "4️⃣  FILES INCLUDED"
echo ""
echo "   CODE SAMPLES:"
echo "   • vulnerable_app.py    (9 security issues)"
echo "   • vulnerable_js.js     (12 security issues)"
echo "   • vulnerable_sql.sql   (10 security issues)"
echo ""
echo "   DOCUMENTATION:"
echo "   • GUIA_PRUEBAS.md      (Full guide - Spanish)"
echo "   • README.md            (Quick reference)"
echo "   • test_urls.txt        (Test URLs collection)"
echo ""
echo "   LAUNCHERS:"
echo "   • launch_vulnerable_apps.ps1  (PowerShell - Recommended)"
echo "   • launch_vulnerable_apps.bat  (CMD - Basic)"
echo ""

print_section "5️⃣  PROGRESS BARS"
echo ""
echo "   SAST Progress:"
echo "   ├─ Status: 'Iniciando...'"
echo "   ├─ Analysis: 'Analizando con BANDIT...'"
echo "   └─ Complete: ✅ Análisis completado (Green, 100%)"
echo ""
echo "   DAST Progress:"
echo "   ├─ Status: 'Iniciando...'"
echo "   ├─ Analysis: 'Ejecutando escaneo dinámico...'"
echo "   └─ Complete: ✅ Análisis completado (Green, 100%)"
echo ""

print_section "6️⃣  SERVICES STATUS"
echo ""
echo "   Backend:  http://127.0.0.1:8000  [✅ RUNNING]"
echo "   Frontend: http://localhost:5173   [✅ RUNNING]"
echo "   Database: SQLite                  [✅ INITIALIZED]"
echo ""

print_section "7️⃣  TROUBLESHOOTING"
echo ""
echo "   Problem: Progress bar not showing"
echo "   Solution: Refresh browser (F5), check DevTools console"
echo ""
echo "   Problem: DAST URL not responding"
echo "   Solution: Verify URL is online, try https:// instead"
echo ""
echo "   Problem: File upload fails"
echo "   Solution: Use .py file, max 10MB, check backend logs"
echo ""
echo "   Problem: Bandit not working"
echo "   Solution: Run: pip install bandit"
echo ""

print_section "8️⃣  NEXT STEPS FOR THESIS"
echo ""
echo "   1. ✓ Run SAST scan → screenshot"
echo "   2. ✓ Run DAST scan → screenshot"
echo "   3. ✓ Capture progress bars → evidence"
echo "   4. ✓ Record metrics → Chapter 4"
echo "   5. ✓ Compare results → validation"
echo "   6. ✓ Document findings → conclusions"
echo ""

print_section "9️⃣  IMPORTANT NOTES"
echo ""
echo "   • HMR Enabled: Changes auto-apply in browser"
echo "   • CORS Configured: Backend ↔ Frontend communication"
echo "   • Database: Persists in database/hybridsecscan.db"
echo "   • Logs: Check terminal for detailed info"
echo "   • Safe: Testing on localhost only"
echo ""

print_section "🔟 USEFUL LINKS"
echo ""
echo "   HybridSecScan:       ../README.md"
echo "   Full Guide:          ./GUIA_PRUEBAS.md"
echo "   Test URLs:           ./test_urls.txt"
echo "   This Reference:      ./QUICK_REFERENCE.md"
echo ""
echo "   Bandit Docs:         https://bandit.readthedocs.io/"
echo "   OWASP ZAP:           https://www.zaproxy.org/"
echo "   OWASP Top 10:        https://owasp.org/www-project-top-ten/"
echo ""

print_section "READY TO TEST!"
echo ""
echo "   Open: http://localhost:5173 and start testing! 🚀"
echo ""
